### ISSUE TITLE
interruptbutton stops working after some time

### ISSUE THREAD

**Issue by goutamreddy** [rwmingis/InterruptButton#14]
Hi,

I'm using your library (thank you for making it!) as a component with esp-idf 4.4.2 on a TTGO T-Display (dual-core ESP32 V3).

**I noticed that after some amount of time, the buttons become unresponsive -  trying to figure out why.**

  Setting up the modules as such:

```
InterruptButton button_bottom(BUTTON_1, LOW);
InterruptButton button_top(BUTTON_2, LOW);
```
```

void buttonSetup()
{
  InterruptButton::setMenuCount(0);
  InterruptButton::setMenuLevel(0);               // Use the functions bound to the first menu associated with the button
  //InterruptButton::m_RTOSservicerStackDepth = 4096; // Use larger values for more memory intensive functions if using Asynchronous mode.
  InterruptButton::setMode(Mode_Asynchronous);    // Defaults to Asynchronous (immediate like an ISR and not actioned in main loop)
  buttonPressActions();
}
```

```
void buttonPressActions() {
  button_top.bind(Event_LongKeyPress, 0, []() {   // LONG PRESS ON BUTTON 2
      displayLCD(LCD_Something);
  });

  button_top.bind(Event_KeyPress, 0, []() {   // PRESS ON BUTTON 2
      displayLCD(LCD_Something);
  });

  button_top.bind(Event_DoubleClick, 0, []() {   // DOUBLE-CLICK ON BUTTON 2
      displayLCD(LCD_Something);
  });

  button_bottom.bind(Event_KeyPress, 0, []() {  // PRESS ON BUTTON 1
      displayLCD(LCD_Something);
  });

  button_bottom.bind(Event_DoubleClick, 0, []() {  // DOUBLE-CLICK ON BUTTON 1
      displayLCD(LCD_Something);
  });
}
```

Behavior- after some unknown amount of time, the button events stop being triggered.   No errors.  No stack overflows.  It appears the rest of program execution keeps chugging along.

**Comment by rwmingis** [comment]
Hi There goutamreddy,

Glad to hear you are liking the library, bit sorry to hear you are having a
bit of strife here.

Am travelling for work ATM so a bit short of time but, in the meantime, a
few things come to mind:

   - The library always uses interrupts to detect a key press.  Perhaps
   something in the IDF code, or perhaps, maybe less likely, the routine
   'displayLCD' is changing interrupts or masks so that the presses are never
   detected.  You can add a few serial debug lines to to the entry portion of
   the ISR to see if it's being triggered as a first pass to debug
   - The asynchronous mode uses an RTOS task which also requires a bit of
   dedicated memory (which you can change the default allotment)  Perhaps
   something is going awry here.  To test this, you could change to the
   Synchronous mode and add in the main loop hook to see if the issue persists
   (would at least isolate RTOS issues)
   - Perhaps there is something wrong with the logic servicing the stack
   for either mode (async or sync) but have not experienced it myself yet
   (mine has run for months at a time with no issues)
   - Maybe ESPIDF or chip specific  I am only running Arduino platform with
   TTGO's myself and all i have tested thus far.

Will have a better look when I return home but those are my first
thoughts.  Let me know how you go with any testing relative to the notes
above .

Cheers

Rob

**Comment by goutamreddy** [comment]
Hi Rob,

Thanks for getting back and for the suggestions.  

Turns out I had some firmware updating code that disabled actions from the buttons and our OTA code was getting caught after an aborted fw update in an erroreous state.... which is to say the problem lay with our code- not yours -  sorry to bother.
